services:
  - type: static
    name: metric-master
    env: static
    rootDir: metric-master
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    autoDeploy: true